title: Phoenix Guild Hub
email: buinoff@gmail.com

google_apps_script_url: https://script.google.com/macros/s/AKfycbzoONZwNyNWDNIsZhkI8nznSSHcP1qzVfL0cRqzLgerj-c10TDNJk-XA6lbtpjVWE0/exec
google_sheet_id: 17VXVPCC3wpbbVwGBQGDMMzAv-CgGsvDhZ26t6bKvmcA

description: >-
  Портал гильдий True Phoenix и Phoenix Nest.

markdown: kramdown

plugins:
  - jekyll-feed

defaults:
  - scope:
      path: "nest"
    values:
      layout: "nest-default"
      author: "Phoenix Nest Team"

  - scope:
      path: ""
    values:
      layout: "true-default"

collections:
  guides:
    output: true
    permalink: /nest/useful/guides/:slug/
  vacancies:
    output: true
    permalink: /nest/vacancies/:slug/

exclude:
  - vendor/
  - .bundle/
  - .github/
  - README.md

permalink: pretty