backend:
  name: github
  repo: Phoenix-Guilds/phoenix-guilds.github.io
  branch: main
  base_url: https://decap-cms-oauth-proxy.vercel.app
  auth_endpoint: auth

publish_mode: editorial_workflow

media_folder: "nest/assets/images/uploads"
public_folder: "/nest/assets/images/uploads"

markdown: kramdown

collections:
  - name: "guides"
    label: "Гайды"
    folder: "_guides"
    create: true

    slug: "{{slug}}"
    summary: '{{title}} — {{author}}' 
    image_field: thumbnail
    
    identifier_field: slug

    fields:
      - { label: "Layout", name: "layout", widget: "hidden", default: "nest-guide" }
      - { label: "Заголовок", name: "title", widget: "string", required: false }
      - { label: "Автор", name: "author", widget: "string", default: "", required: false }
      - { 
          label: "Обложка (для плитки в админке)", 
          name: "thumbnail", 
          widget: "image", 
          required: false,
          hint: "Эта картинка будет отображаться в сетке гайдов в админке",
        }
      - { label: "Краткое описание", name: "description", widget: "text", required: false }
      - { label: "Текст гайда", name: "body", widget: "markdown" }

  - name: "vacancies"
    label: "Вакансии"
    folder: "_vacancies"
    create: true

    slug: "{{slug}}"
    summary: '{{title}} — {{description}}'

    identifier_field: slug

    fields:
      - { label: "Layout", name: "layout", widget: "hidden", default: "nest-vacancy" }
      - { label: "Заголовок", name: "title", widget: "string", required: false }
      - { label: "Краткое описание", name: "description", widget: "text", required: false }
      - { label: "Общее количество мест", name: "slots_total", widget: "number", required: false, default: 1, min: 0 }
      - { label: "Занято мест", name: "slots_filled", widget: "number", required: false, default: 0, min: 0 }
      - { label: "Требования", name: "requirements", widget: "markdown", required: false, hint: "Перечислите требования к кандидату" }
      - { label: "Описание вакансии", name: "body", widget: "markdown", required: false }
