backend:
  name: github
  repo: Phoenix-Guilds/phoenix-guilds.github.io
  branch: main
  base_url: https://decap-cms-oauth-proxy.vercel.app
  auth_endpoint: auth

media_folder: "nest/assets/images/uploads"
public_folder: "/nest/assets/images/uploads"

collections:
  - name: "guides"
    label: "Гайды"
    folder: "_guides"
    create: true
    slug: "{{slug}}"
    identifier_field: slug
    fields:
      - { label: "Layout", name: "layout", widget: "hidden", default: "nest-guide" }
      - { label: "Заголовок", name: "title", widget: "slugger" }
      - { label: "Slug", name: "slug", widget: "string", required: false }
      - { label: "Автор", name: "author", widget: "string", default: "" }
      - { label: "Краткое описание", name: "description", widget: "text" }
      - { label: "Текст гайда", name: "body", widget: "markdown" }