backend:
  name: git-gateway
  repo: Phoenix-Guilds/phoenix-guilds.github.io
  branch: main

media_folder: "nest/assets/images/uploads"
public_folder: "/nest/assets/images/uploads"

collections:
  - name: "guides"
    label: "Гайды"
    files:
      - name: "hc-leveling"
        label: "Гайд по прокачке ХК от Сильмы"
        file: "nest/guides/hc-leveling.md"
        fields:
          - { label: "Заголовок", name: "title", widget: "string" }
          - { label: "Текст гайда", name: "body", widget: "markdown" }