name: Slugify

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  slugify:
    if: github.event.head_commit.message != 'Auto slugify filenames'
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Slugify filenames
        run: python3 .github/scripts/slugify_filenames.py

      - name: Commit changes
        run: |
          git config user.name "slug-bot"
          git config user.email "slug-bot@users.noreply.github.com"

          if git diff --cached --quiet; then
            echo "No changes to commit"
          else
            git commit -m "Auto slugify filenames"
            git push
          fi